### ISSUE TITLE
Browser "No Method Error" for 'Login' Code -Future Lesson

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/sinatra-using-erb#12]
Hi, followed along with this CodeAlong Lesson, using prior lab "Sinatra Basic Views Lab" per instructions.  

After typing this in:

<% if 1 == 2 %>
  <p>1 equals 2.</p>
<% else %>
  <p>1 does not equal 2.</p>
<% end %>

I then typed this in:

<% if logged_in? %>
  <a href="/logout">Click here to Log Out</a>
<% else %>
  <a href="/login">Click here to Log In</a>
<% end %>

I received in-browser Error Message about "No Method Login" pointing to the line with error. I could not get it to work. 

I did this: 
************
1. Typed code by hand. Errored
2. Copied/pasted all code again.  Still errored. 
3. Did screen share with AAQ. We commented out the second part. Same error. 
4. Only by deleting  the 2nd part (>% if logged_in? etc  )  did the expected code appear in browser from implementing Shotgun. 

* AAQ said the login errors and stuff would not come in curriculum until several lessons ahead, in Sinatra Sessions.  

* Suggestion: Advise students not to type in the login code (tell them the FB example is not to be coded).  Thanks much.

**Comment by drakeltheryuujin** [comment]
Hi there,

I don't think that this was an expected part of the codealong. In the lesson it says ```However, imagine that you work at Facebook and that you have a method called logged_in?```. It's a hypothetical scenario. Thanks for your contribution!
