### ISSUE TITLE
bundle failed

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co-curriculum/sinatra-using-erb#3]
had to run `gem install eventmachine -v 1.0.8 -- --with-cppflags=-I/usr/local/opt/openssl/include` to fix

**Comment by jmburges** [comment]
@vicfriedman can you install a fresh version of ruby (in rvm, just install some other version then what you have) and do a bundle install to see if this is an issue?

**Comment by victhevenot** [comment]
@jmburges worked using Ruby ruby 2.2.2p95 and  2.2.3

**Comment by jmburges** [comment]
hmmmm must have been an issue with his machine then
